import './globals.css'
import { Navigation } from '@/components/Navigation'
import { Footer } from '@/components/Footer'

export const metadata = {
  title: 'My first Next.js app',
  description: 'Generated by create next app',
  keywords: 'next, react, app',

}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='menu-top'>
          <Navigation></Navigation>
        </div>
        <div className='content'>
          {children}
        </div>
      </body>
      <footer className='site-footer'>
        <div>
          <Footer></Footer>
        </div>
      </footer>
    </html>
  )
}
